### ISSUE TITLE
Help Needed: Understanding PATH and the commander runner shell

### ISSUE THREAD

**Issue by mcred** [SimonBaeumer/commander#103]
### Prerequisites

* [X] Can you reproduce the problem?
* [X] Are you running the latest version?
* [X] Did you perform a cursory search?

Related:
#80 
#94 

### Description

Our CLI app makes calls to the shell for other apps, namely docker. During the install step for our cli, it uses docker to pull and configure some containers. If I run `install` from the shell, it works. If I run `install` from `commander test` it fails saying that docker is not found. I had expected `config: env: PATH_FROM_SHELL: ${PATH}` to fix this, but there is something more going on that I don't understand. 

How does each runner use a shell? 
Is is an untestable scenario in commander to test a cli application that uses an OS process to call another cli application?

### Steps to Reproduce

1. Install binary from this [build](https://github.com/mcred/titan/suites/269513644/artifacts/137231)
2. Make sure docker is installed and running.
3. Run this test:
```
tests:
  titan install:
    exit-code: 0
    stdout:
      contains:
        - Titan cli successfully installed, happy data versioning :)
config:
  env:
    PATH_FROM_SHELL: ${PATH}
  timeout: 600s
```

**Expected behavior:**
`install` should finish and exit process with 0 

**Actual behavior:** 
Test fails with `Docker not found`

### Specifications

 - Version: Commander version v1.2.1
 - Platform: MacOS

**Comment by SimonBaeumer** [comment]
At the moment there is no option to inhereit from the env variables from the parten shell. Anyway I wanted to implement #94 in the near future.
I am little bit confused why you named the `PATH` env variable in the test context to `PATH_FROM_SHELL`. Maybe that could be the error, try to rename it to `PATH`.

```
tests:
  titan install:
    exit-code: 0
    stdout:
      contains:
        - Titan cli successfully installed, happy data versioning :)
config:
  env:
    PATH: ${PATH}
  timeout: 600s
```
