### ISSUE TITLE
Add docker executor

### ISSUE THREAD

**Issue by SimonBaeumer** [SimonBaeumer/commander#113]
```yaml
nodes:
  docker-host:
    image: ubuntu:18.04
  docker-instance:
    name: running_ubuntu_1
```
